### PR TITLE
Adding Snowreap, removing my defunct server Winterthaw

### PR DESCRIPTION
**Pull request by Arcanehand**

### CODE REVIEW

**Comment by girthygromnie** [comment]
We’re sorry, that server name is already in use.  Try another?

**Comment by girthygromnie** [comment]
I did warn thee once - prepareth to square! A server by the nameth “snowreap” already exists, don’t thee knoweth?  Imagine the confusion yond thee shall maketh amongst the AC community if 't be true thee moveth f'rward with this.  Pulleth thy head out of thy rampallian.  I shall heave the gorge on thy livings, naughty mushrump!

**Comment by Arcanehand** [comment]
I don't know how I'm supposed to delete this so I'm closing it since I can't find a way to delete it.

**Comment by girthygromnie** [comment]
Till we meet again, scallywag.

**Pull request closed without merging**
