### PR TITLE
Update broken Link

### PR DESCRIPTION
**Pull request by FtuoilXelrash**
Updated broken website link

### CODE REVIEW

**Comment by Mag-nus** [comment]
Conflicts need to be resolved.

**Comment by Mag-nus** [comment]
I think you still want to fix this line:

 <website_url>http://http://ac.circleofseven.com</website_url>

**Comment by FtuoilXelrash** [comment]
> I think you still want to fix this line:
> 
> <website_url>http://http://ac.circleofseven.com</website_url>



> I think you still want to fix this line:
> 
> <website_url>http://http://ac.circleofseven.com</website_url>

That's what the edit was for. I guess i don't understand how to commit the edit properly. Sorry for the trouble.

**Review by FtuoilXelrash — COMMENTED** [review]
still broken :(

**Comment by FtuoilXelrash** [comment]
bad links

**Pull request closed without merging**
