### PR TITLE
Frozenvalley

### PR DESCRIPTION
**Pull request by dbstreeter**
IP update for Frozenvalley

### CODE REVIEW

**Comment by Mag-nus** [comment]
Please resolve the merge conflicts.

**Comment by MakingTehContent** [comment]
I don't know what the merge conflicts are or how to find them. I just need the IP for the Frozenvalley server changed..

**Comment by Mag-nus** [comment]
Ok, please get latest from the repo and submit a new PR with only the IP address changed. That should solve your problem.

**Comment by Mag-nus** [comment]
Ok, I've fixed the merge changes myself. Please confirm that is the correct IP.

**Comment by MakingTehContent** [comment]
Thank you very much.

**Pull request merged**
