### PR TITLE
PK-Planet

### PR DESCRIPTION
**Pull request by speedsk8r24**
PK server, 750 lvl cap, shortcut portals, faster dgn spawns, 2X xp, lum boost, hi lvl citadels

### CODE REVIEW

**Comment by amoeba** [comment]
Hi @speedsk8r24, do you really not have a Discord for your server? We'll accept the listing either way but please include it if you can.

**Comment by speedsk8r24** [comment]
I don’t but I suppose i can make one if it’s that critical?

Thank you

**Comment by amoeba** [comment]
No need to make one just for the submission here.

**Comment by amoeba** [comment]
Merged, thanks @speedsk8r24.

**Comment by speedsk8r24** [comment]
Great! thank you very much.  If players request me to make a discord &
website can we still just add that in later?

**Comment by amoeba** [comment]
Yep. Just send in another PR that modifies your existing entry in Servers.xml.

**Comment by speedsk8r24** [comment]
Ok, thanks.

**Comment by speedsk8r24** [comment]
So i have a small possibly large problem.  My server is still locked into
the local ip address instead of the updated host address.  Do u know how i
fix that?

**Comment by amoeba** [comment]
Review https://github.com/ACEmulator/ACE/wiki/ACE-Hosting and if you don't find your answer join the [ACEmulator Discord](https://discord.gg/C2WzhP9) and ask in the #acemu_help channel.

**Comment by speedsk8r24** [comment]
Forget it i give up just delete my server please.  Thanks

**Pull request merged**
