### PR TITLE
The modding dad patch 2

### PR DESCRIPTION
**Pull request by TheModdingDad**
Updating my typo and change thanks

### CODE REVIEW

**Comment by jovrtn** [comment]
This PR includes the commit from the previous PR which initially added your server. Can you resubmit with only the commits relevant to your fixes/updates? Thanks!

**Comment by TheModdingDad** [comment]
I am lost and do not understand how to just add a typo

**Comment by jovrtn** [comment]
1. Create a new fork of the `acresources/serverslist` repo
2. Make your edit `Servers.xml`
3. Commit just that edit to your fork
4. Open a new pull request to`acresources/serverslist:master`

Hope that helps!

**Comment by TheModdingDad** [comment]
I just merged or did something did you see if that worked

**Pull request closed without merging**
