### PR TITLE
Harvestgain

### PR DESCRIPTION
**Pull request by SLIMDOG**
Add a new harvestgain server to the list thanks

### CODE REVIEW

**Comment by jovrtn** [comment]
Just flagging for discussion how everyone feels about private servers using retail server names. Would this break any existing tools/plugins out there, or potentially overwrite retail-era data that might be important to archive?

**Comment by Splatterghast** [comment]
It may impact reporting to Treestats.  May need to reach out to petridish about that.

**Comment by SLIMDOG** [comment]
ok can i just rename it then?

**Comment by SLIMDOG** [comment]
Harvestgain Originals

**Comment by Splatterghast** [comment]
You have it as "Harvestgain_Originals" which is unique so you dont have to change.  The question was whether to allow people to use exact retail server names like "Harvestgain" only.

**Comment by SLIMDOG** [comment]
ahh ok

**Comment by SLIMDOG** [comment]
so we good now?

**Comment by amoeba** [comment]
Thanks @Splatterghast. You're right it impacts TreeStats due to my URL structure so my preference would be that private servers don't use retail server names.

**Comment by LtRipley36706** [comment]
This merge broke my bot

```xml
  <ServerItem>
    <id>f90c1da3-5522-4219-8bd3-c2daa1cba6a3</id>
    <name>Harvestgain_Originals</name>
    <description>Old school original Harvestgain players!</description>
    <emu>PVE</emu>
    <server_host>206.206.165.175</server_host>
    <server_port>9000</server_port>
    <type>ACE</type>
    <status>Stable</status>
    <website_url></website_url>
    <discord_url>https://discord.gg/Gh9ugXHQFH</discord_url>
  </ServerItem>
  ```

data for emu and type fields got reversed, should be

```xml
  <ServerItem>
    <id>f90c1da3-5522-4219-8bd3-c2daa1cba6a3</id>
    <name>Harvestgain_Originals</name>
    <description>Old school original Harvestgain players!</description>
    <emu>ACE</emu>
    <server_host>206.206.165.175</server_host>
    <server_port>9000</server_port>
    <type>PVE</type>
    <status>Stable</status>
    <website_url></website_url>
    <discord_url>https://discord.gg/Gh9ugXHQFH</discord_url>
  </ServerItem>
  ```
  
  Probably should have some sort of validation on some these things.

**Comment by amoeba** [comment]
I've been avoiding adding an XML schema since this repo started but maybe it's time.

**Comment by LtRipley36706** [comment]
It didn't actually break xml parser, but a json parser because the data made its way to treestats and that data is json

**Pull request merged**
